//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationManger.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OperationManger.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your question has been successfully entered.
        /// </summary>
        public static string DataIsEnterd {
            get {
                return ResourceManager.GetString("DataIsEnterd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the end caption..
        /// </summary>
        public static string EndCaptionEmptyMessage {
            get {
                return ResourceManager.GetString("EndCaptionEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end caption should not contain numbers only..
        /// </summary>
        public static string EndCaptionJustNumberMessage {
            get {
                return ResourceManager.GetString("EndCaptionJustNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end value must be less than 100..
        /// </summary>
        public static string EndValueGreaterThanOneHundredMessage {
            get {
                return ResourceManager.GetString("EndValueGreaterThanOneHundredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end value must be greater than 0..
        /// </summary>
        public static string EndValueLessThanZeroMessage {
            get {
                return ResourceManager.GetString("EndValueLessThanZeroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems in database.
        /// </summary>
        public static string ErrorDataBase {
            get {
                return ResourceManager.GetString("ErrorDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems in database while adding question.
        /// </summary>
        public static string ErrorDataBaseAddQuestion {
            get {
                return ResourceManager.GetString("ErrorDataBaseAddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems in database in connection string.
        /// </summary>
        public static string ErrorDataBaseConnectionString {
            get {
                return ResourceManager.GetString("ErrorDataBaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems in database while deleting question.
        /// </summary>
        public static string ErrorDataBaseDeleteQuestion {
            get {
                return ResourceManager.GetString("ErrorDataBaseDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems in database while editting question.
        /// </summary>
        public static string ErrorDataBaseEditQuestion {
            get {
                return ResourceManager.GetString("ErrorDataBaseEditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems in database while getting question.
        /// </summary>
        public static string ErrorDataBaseGetQuestion {
            get {
                return ResourceManager.GetString("ErrorDataBaseGetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems in database while selecting question.
        /// </summary>
        public static string ErrorDataBaseSelectQuestion {
            get {
                return ResourceManager.GetString("ErrorDataBaseSelectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot find this question..
        /// </summary>
        public static string ErrorInOperation {
            get {
                return ResourceManager.GetString("ErrorInOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems in operation manger.
        /// </summary>
        public static string ErrorManger {
            get {
                return ResourceManager.GetString("ErrorManger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was some problem in Operations Manager when adding a question.
        /// </summary>
        public static string ErrorMangerAddQuestion {
            get {
                return ResourceManager.GetString("ErrorMangerAddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems in operation manger when deleting question.
        /// </summary>
        public static string ErrorMangerDeleteQuestion {
            get {
                return ResourceManager.GetString("ErrorMangerDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems in operation manger when editing question.
        /// </summary>
        public static string ErrorMangerEditQuestion {
            get {
                return ResourceManager.GetString("ErrorMangerEditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems in operation manger when getting question.
        /// </summary>
        public static string ErrorMangerGetQuestion {
            get {
                return ResourceManager.GetString("ErrorMangerGetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to the database , something went wrong.
        /// </summary>
        public static string ErrorWhileConnectiong {
            get {
                return ResourceManager.GetString("ErrorWhileConnectiong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some problems with your form submission.
        /// </summary>
        public static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order must be more than 0.
        /// </summary>
        public static string NewOrderLessThanZeroMessage {
            get {
                return ResourceManager.GetString("NewOrderLessThanZeroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select any question!.
        /// </summary>
        public static string NoSelectItem {
            get {
                return ResourceManager.GetString("NoSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the question type!.
        /// </summary>
        public static string NotChooseTheType {
            get {
                return ResourceManager.GetString("NotChooseTheType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of smile faces must be between 2 and 5.
        /// </summary>
        public static string NumberOfSmileBetweenFiveAndTow {
            get {
                return ResourceManager.GetString("NumberOfSmileBetweenFiveAndTow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of stars must be between 1 and 10.
        /// </summary>
        public static string NumberOfStrasBetweenTenAndOne {
            get {
                return ResourceManager.GetString("NumberOfStrasBetweenTenAndOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter text.
        /// </summary>
        public static string QuestionIsEmptyMessage {
            get {
                return ResourceManager.GetString("QuestionIsEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question should not contain numbers only.
        /// </summary>
        public static string QuestionIsJustANumberMessage {
            get {
                return ResourceManager.GetString("QuestionIsJustANumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the start caption.
        /// </summary>
        public static string StartCaptionEmptyMessage {
            get {
                return ResourceManager.GetString("StartCaptionEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start caption should not contain numbers only.
        /// </summary>
        public static string StartCaptionJustNumberMessage {
            get {
                return ResourceManager.GetString("StartCaptionJustNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start value must be less than 100.
        /// </summary>
        public static string StartValueGreaterThanOneHundredMessage {
            get {
                return ResourceManager.GetString("StartValueGreaterThanOneHundredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start value must be greater than 0.
        /// </summary>
        public static string StartValueLessThanZeroMessage {
            get {
                return ResourceManager.GetString("StartValueLessThanZeroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this question?.
        /// </summary>
        public static string SureToDeleteMessage {
            get {
                return ResourceManager.GetString("SureToDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your question has been edit successfully.
        /// </summary>
        public static string TheEditMessage {
            get {
                return ResourceManager.GetString("TheEditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end value should not be smaller than the start value.
        /// </summary>
        public static string TheEndValueSholudGreaterThanStartValueMessage {
            get {
                return ResourceManager.GetString("TheEndValueSholudGreaterThanStartValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order number is empty.
        /// </summary>
        public static string TheOrderIsEmpty {
            get {
                return ResourceManager.GetString("TheOrderIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your question has been delete successfully.
        /// </summary>
        public static string TheQuestionDeleted {
            get {
                return ResourceManager.GetString("TheQuestionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your question has not been deleted..
        /// </summary>
        public static string TheQuestionNotDeleted {
            get {
                return ResourceManager.GetString("TheQuestionNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question.
        /// </summary>
        public static string TitleOfQuestionAdd {
            get {
                return ResourceManager.GetString("TitleOfQuestionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Question.
        /// </summary>
        public static string TitleOfQuestionEdit {
            get {
                return ResourceManager.GetString("TitleOfQuestionEdit", resourceCulture);
            }
        }
    }
}
