//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyWebSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurveyWebSite.Resources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteView {
            get {
                return ResourceManager.GetString("DeleteView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditView {
            get {
                return ResourceManager.GetString("EditView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndCaption.
        /// </summary>
        public static string EndCaption {
            get {
                return ResourceManager.GetString("EndCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndValue.
        /// </summary>
        public static string EndValue {
            get {
                return ResourceManager.GetString("EndValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string ErrorNotFound {
            get {
                return ResourceManager.GetString("ErrorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorView.
        /// </summary>
        public static string ErrorView {
            get {
                return ResourceManager.GetString("ErrorView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeView {
            get {
                return ResourceManager.GetString("HomeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdForType.
        /// </summary>
        public static string IdForType {
            get {
                return ResourceManager.GetString("IdForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewText.
        /// </summary>
        public static string NewText {
            get {
                return ResourceManager.GetString("NewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfSmiles.
        /// </summary>
        public static string NumberOfSmiles {
            get {
                return ResourceManager.GetString("NumberOfSmiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfStars.
        /// </summary>
        public static string NumberOfStar {
            get {
                return ResourceManager.GetString("NumberOfStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ListPartail.
        /// </summary>
        public static string PartailList {
            get {
                return ResourceManager.GetString("PartailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SliderPartail.
        /// </summary>
        public static string PartailSlider {
            get {
                return ResourceManager.GetString("PartailSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SmilePartail.
        /// </summary>
        public static string PartailSmile {
            get {
                return ResourceManager.GetString("PartailSmile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _StarPartail.
        /// </summary>
        public static string PartailStar {
            get {
                return ResourceManager.GetString("PartailStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartCaption.
        /// </summary>
        public static string StartCaption {
            get {
                return ResourceManager.GetString("StartCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartValue.
        /// </summary>
        public static string StartValue {
            get {
                return ResourceManager.GetString("StartValue", resourceCulture);
            }
        }
    }
}
