//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyWebSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurveyWebSite.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Question.
        /// </summary>
        public static string CreateNewQuestion {
            get {
                return ResourceManager.GetString("CreateNewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Question.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider question has been Edited successfully.
        /// </summary>
        public static string EditQuestionSlider {
            get {
                return ResourceManager.GetString("EditQuestionSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smile question has been Edited successfully.
        /// </summary>
        public static string EditQuestionSmile {
            get {
                return ResourceManager.GetString("EditQuestionSmile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star question has been Edited successfully.
        /// </summary>
        public static string EditQuestionStar {
            get {
                return ResourceManager.GetString("EditQuestionStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Edit.
        /// </summary>
        public static string EditSlider {
            get {
                return ResourceManager.GetString("EditSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smile Edit.
        /// </summary>
        public static string EditSmile {
            get {
                return ResourceManager.GetString("EditSmile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Edit.
        /// </summary>
        public static string EditStar {
            get {
                return ResourceManager.GetString("EditStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndCaption.
        /// </summary>
        public static string EndCaption {
            get {
                return ResourceManager.GetString("EndCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndValue.
        /// </summary>
        public static string EndValue {
            get {
                return ResourceManager.GetString("EndValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong while change language in home controller.
        /// </summary>
        public static string ErrorChangeLanguage {
            get {
                return ResourceManager.GetString("ErrorChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong while create in controller.
        /// </summary>
        public static string ErrorCreate {
            get {
                return ResourceManager.GetString("ErrorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong while delete in controller.
        /// </summary>
        public static string ErrorDelete {
            get {
                return ResourceManager.GetString("ErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong while edit in controller.
        /// </summary>
        public static string ErrorEdit {
            get {
                return ResourceManager.GetString("ErrorEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong while getting question in home controller.
        /// </summary>
        public static string ErrorHome {
            get {
                return ResourceManager.GetString("ErrorHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the order filed !.
        /// </summary>
        public static string ErrorMessageForOrder {
            get {
                return ResourceManager.GetString("ErrorMessageForOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the question filed !.
        /// </summary>
        public static string ErrorMessageForText {
            get {
                return ResourceManager.GetString("ErrorMessageForText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong while refresh question in home controller.
        /// </summary>
        public static string ErrorRefrsh {
            get {
                return ResourceManager.GetString("ErrorRefrsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Smile Faces.
        /// </summary>
        public static string NumberOfSmileFaces {
            get {
                return ResourceManager.GetString("NumberOfSmileFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Stars.
        /// </summary>
        public static string NumberOfStars {
            get {
                return ResourceManager.GetString("NumberOfStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string QuestionOrder {
            get {
                return ResourceManager.GetString("QuestionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string QuestionText {
            get {
                return ResourceManager.GetString("QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Question.
        /// </summary>
        public static string QuestionType {
            get {
                return ResourceManager.GetString("QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        public static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smile.
        /// </summary>
        public static string Smile {
            get {
                return ResourceManager.GetString("Smile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong !.
        /// </summary>
        public static string SomeThingWrong {
            get {
                return ResourceManager.GetString("SomeThingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        public static string Star {
            get {
                return ResourceManager.GetString("Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartCaption.
        /// </summary>
        public static string StartCaption {
            get {
                return ResourceManager.GetString("StartCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartValue.
        /// </summary>
        public static string StartValue {
            get {
                return ResourceManager.GetString("StartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this question?.
        /// </summary>
        public static string SureForDelete {
            get {
                return ResourceManager.GetString("SureForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your question has been edit successfully.
        /// </summary>
        public static string TheEditMessage {
            get {
                return ResourceManager.GetString("TheEditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end value must be greater than the start value.
        /// </summary>
        public static string TheEndValueSholudGreaterThanStartValueMessage {
            get {
                return ResourceManager.GetString("TheEndValueSholudGreaterThanStartValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Questions.
        /// </summary>
        public static string TitleHome {
            get {
                return ResourceManager.GetString("TitleHome", resourceCulture);
            }
        }
    }
}
